"""empty message

Revision ID: 043ccc001d47
Revises: 39d20cc8749f
Create Date: 2024-05-07 17:10:07.402439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '043ccc001d47'
down_revision: Union[str, None] = '39d20cc8749f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('basket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product', sa.String(), nullable=True),
    sa.Column('menu_name', sa.String(), nullable=True),
    sa.Column('miqdor', sa.Integer(), nullable=True),
    sa.Column('narx', sa.BigInteger(), nullable=True),
    sa.Column('chat_id', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('basket')
    # ### end Alembic commands ###
