"""empty message

Revision ID: 087e4c94bdca
Revises: b919cb543653
Create Date: 2024-02-16 20:31:03.040892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '087e4c94bdca'
down_revision: Union[str, None] = 'b919cb543653'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('basket',
    sa.Column('product', sa.String(), nullable=True),
    sa.Column('miqdor', sa.Integer(), nullable=True),
    sa.Column('narx', sa.BigInteger(), nullable=True),
    sa.Column('chat_id', sa.BigInteger(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('basket')
    # ### end Alembic commands ###
