"""empty message

Revision ID: 2121dea547a9
Revises: b418a60f9762
Create Date: 2024-04-21 01:52:05.961601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2121dea547a9'
down_revision: Union[str, None] = 'b418a60f9762'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history_buys',
    sa.Column('number', sa.BigInteger(), nullable=True),
    sa.Column('product', sa.String(), nullable=True),
    sa.Column('miqdor', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('bought_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('payment_method', sa.String(), nullable=True),
    sa.Column('payment_status', sa.String(), nullable=True),
    sa.Column('go_or_order', sa.String(), nullable=True),
    sa.Column('which_filial', sa.String(), nullable=True),
    sa.Column('chat_id', sa.BigInteger(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('history_buys')
    # ### end Alembic commands ###
