"""empty message

Revision ID: 2b93143994f6
Revises: 1d15bea8e789
Create Date: 2024-02-16 21:49:42.576553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b93143994f6'
down_revision: Union[str, None] = '1d15bea8e789'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('basket', sa.Column('menu_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('basket', 'menu_name')
    # ### end Alembic commands ###
