"""empty message

Revision ID: 2d39958c7c1b
Revises: 81c3e36fd85a
Create Date: 2024-03-10 04:22:39.686553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d39958c7c1b'
down_revision: Union[str, None] = '81c3e36fd85a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history_buys', sa.Column('which_filial', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('history_buys', 'which_filial')
    # ### end Alembic commands ###
