"""empty message

Revision ID: 35c3dec6b06f
Revises: 0a20b04aeb7f
Create Date: 2024-03-08 22:45:42.773162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35c3dec6b06f'
down_revision: Union[str, None] = '0a20b04aeb7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filial_admins',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('which_filial', sa.String(), nullable=True),
    sa.Column('chat_id', sa.BigInteger(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('filial_admins')
    # ### end Alembic commands ###
