"""empty message

Revision ID: 35cdf7ef82a0
Revises: 413203332a1e
Create Date: 2024-03-17 15:39:02.416573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35cdf7ef82a0'
down_revision: Union[str, None] = '413203332a1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('filial_admins', sa.Column('admin_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('filial_admins', 'admin_name')
    # ### end Alembic commands ###
