"""empty message

Revision ID: 396d9216ddf8
Revises: 525193fec7ea
Create Date: 2024-05-30 00:14:45.368641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '396d9216ddf8'
down_revision: Union[str, None] = '525193fec7ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('radius',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('radius', sa.Integer(), nullable=True),
    sa.Column('sum', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('radius')
    # ### end Alembic commands ###
