"""empty message

Revision ID: 430530381a3b
Revises: 043ccc001d47
Create Date: 2024-05-20 23:04:14.275494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '430530381a3b'
down_revision: Union[str, None] = '043ccc001d47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history_buys', sa.Column('sent', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('history_buys', 'sent')
    # ### end Alembic commands ###
