"""empty message

Revision ID: 509e11cc85e5
Revises: 2f44db0439c0
Create Date: 2024-02-28 21:52:43.233756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '509e11cc85e5'
down_revision: Union[str, None] = '2f44db0439c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history_buys', sa.Column('price', sa.Integer(), nullable=True))
    op.drop_column('history_buys', 'total_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history_buys', sa.Column('total_price', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('history_buys', 'price')
    # ### end Alembic commands ###
