"""empty message

Revision ID: 525193fec7ea
Revises: 430530381a3b
Create Date: 2024-05-20 23:30:05.343591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '525193fec7ea'
down_revision: Union[str, None] = '430530381a3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('chat_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message_for_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_uz', sa.String(), nullable=True),
    sa.Column('message_ru', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message_for_user')
    op.drop_table('curers')
    # ### end Alembic commands ###
