"""empty message

Revision ID: 5b951f7771c2
Revises: 5532880d8cef
Create Date: 2024-04-21 01:33:43.358527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b951f7771c2'
down_revision: Union[str, None] = '5532880d8cef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('about_we',
    sa.Column('about_we', sa.String(), nullable=True)
    )
    op.create_table('history_buys',
    sa.Column('number', sa.BigInteger(), nullable=True),
    sa.Column('product', sa.String(), nullable=True),
    sa.Column('miqdor', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('bought_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('payment_method', sa.String(), nullable=True),
    sa.Column('payment_status', sa.String(), nullable=True),
    sa.Column('go_or_order', sa.String(), nullable=True),
    sa.Column('which_filial', sa.String(), nullable=True),
    sa.Column('chat_id', sa.BigInteger(), nullable=True)
    )
    op.create_table('socials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('social_name', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('socials')
    op.drop_table('history_buys')
    op.drop_table('about_we')
    # ### end Alembic commands ###
