"""empty message

Revision ID: 5bb1599c47bb
Revises: 363bfaa9da5c
Create Date: 2024-02-10 21:50:48.639864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bb1599c47bb'
down_revision: Union[str, None] = '363bfaa9da5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fast_food_menu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('menu', sa.String(), nullable=True),
    sa.Column('food_name', sa.String(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('photo', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fast_food_menu')
    # ### end Alembic commands ###
