"""empty message

Revision ID: 7bc443656fe3
Revises: b142a83ce497
Create Date: 2024-02-28 21:44:35.994347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bc443656fe3'
down_revision: Union[str, None] = 'b142a83ce497'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ordered')
    op.add_column('history_buys', sa.Column('payment_status', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('history_buys', 'payment_status')
    op.create_table('ordered',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('product', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('miqdor', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('narx', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='ordered_pkey')
    )
    # ### end Alembic commands ###
