"""empty message

Revision ID: 81c3e36fd85a
Revises: c5446ef6e36f
Create Date: 2024-03-09 00:54:27.023416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81c3e36fd85a'
down_revision: Union[str, None] = 'c5446ef6e36f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history_buys', sa.Column('go_or_order', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('history_buys', 'go_or_order')
    # ### end Alembic commands ###
