"""empty message

Revision ID: 8664468821c4
Revises: 2121dea547a9
Create Date: 2024-04-21 01:57:00.108717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8664468821c4'
down_revision: Union[str, None] = '2121dea547a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history_buys', sa.Column('is_waiting', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('history_buys', 'is_waiting')
    # ### end Alembic commands ###
