"""empty message

Revision ID: 8996d91a7893
Revises: 55fae7841670
Create Date: 2024-02-28 18:20:35.617390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8996d91a7893'
down_revision: Union[str, None] = '55fae7841670'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ordered', sa.Column('status', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ordered', 'status')
    # ### end Alembic commands ###
