"""empty message

Revision ID: 95f25d1e64f1
Revises: 0e1d0e598a2f
Create Date: 2024-02-22 19:57:22.501111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95f25d1e64f1'
down_revision: Union[str, None] = '0e1d0e598a2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oredring',
    sa.Column('chat_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('oredring')
    # ### end Alembic commands ###
