"""empty message

Revision ID: b2294a2fb9be
Revises: 5bb1599c47bb
Create Date: 2024-02-11 18:36:42.350553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2294a2fb9be'
down_revision: Union[str, None] = '5bb1599c47bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fast_food_menu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('menu', sa.String(), nullable=True),
    sa.Column('food_name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('photo', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fast_food_menu')
    # ### end Alembic commands ###
