"""empty message

Revision ID: b7f843b9b399
Revises: 55f977005ab6
Create Date: 2024-02-10 21:35:27.973567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7f843b9b399'
down_revision: Union[str, None] = '55f977005ab6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('menu', sa.Column('menu_picture', sa.String(), nullable=True))
    op.add_column('menu', sa.Column('lang', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu', 'lang')
    op.drop_column('menu', 'menu_picture')
    op.drop_table('admins')
    # ### end Alembic commands ###
