"""empty message

Revision ID: b7fd992b2fab
Revises: 2dfdb1118320
Create Date: 2024-02-05 14:49:08.164409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7fd992b2fab'
down_revision: Union[str, None] = '2dfdb1118320'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fast_food_menu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('menu', sa.String(), nullable=True),
    sa.Column('food_name', sa.String(), nullable=True),
    sa.Column('price', sa.String(), nullable=True),
    sa.Column('photo', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fast_food_menu')
    # ### end Alembic commands ###
