"""empty message

Revision ID: c0158646f4b3
Revises: cb6cf51aabe7
Create Date: 2024-02-26 21:43:18.245082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0158646f4b3'
down_revision: Union[str, None] = 'cb6cf51aabe7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('filials', sa.Column('lang', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('filials', 'lang')
    # ### end Alembic commands ###
