"""empty message

Revision ID: cb6cf51aabe7
Revises: 2c4bdc578868
Create Date: 2024-02-26 20:36:16.423041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb6cf51aabe7'
down_revision: Union[str, None] = '2c4bdc578868'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filial_name', sa.String(), nullable=True),
    sa.Column('latitude', sa.String(), nullable=True),
    sa.Column('longitude', sa.String(), nullable=True),
    sa.Column('is_open', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('filials')
    # ### end Alembic commands ###
